# Generated by Django 2.1.15 on 2020-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
