# Generated by Django 2.1.15 on 2020-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange'), ('LSE', 'London Stock Exchange')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollars'), ('GBP', 'Great British Pound')], max_length=5)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trading_date_time', models.DateTimeField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=9)),
                ('charges_fees', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market')], max_length=20)),
                ('execution_venue', models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange'), ('LSE', 'London Stock Exchange'), ('OTC', 'Over the Counter')], max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(choices=[('GBP', 'Great British Pound'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], max_length=3)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
