# Generated by Django 2.1.15 on 2021-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('MARKET_BUY', 'Market buy'), ('DIVIDEND_ORDINARY', 'Dividend (Ordinary)'), ('STOP_LIMIT_SELL', 'Stop Limit Sell'), ('STOP_LIMIT_BUY', 'Stop Limit Buy')], max_length=20)),
                ('time', models.DateTimeField()),
                ('isin', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('share_quantity', models.DecimalField(decimal_places=8, max_digits=19, null=True)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(blank=True, choices=[('GBP', 'Great British Pound'), ('GBX', 'Great British Pound in Pence'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], max_length=20)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('result', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('witholding_tax', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('witholding_tax_currency', models.CharField(blank=True, choices=[('GBP', 'Great British Pound'), ('GBX', 'Great British Pound in Pence'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], max_length=20)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('stamp_duty', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('stamp_duty_reserve_tax', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('finra_fee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
