# Generated by Django 2.1.15 on 2021-01-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210116_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('DIVIDEND_DEMERGER', 'Dividend (Demerger)'), ('DIVIDEND_ORDINARY', 'Dividend (Ordinary)'), ('MARKET_BUY', 'Market buy'), ('MARKET_SELL', 'Market sell'), ('STOP_LIMIT_SELL', 'Stop Limit Sell'), ('STOP_LIMIT_BUY', 'Stop Limit Buy'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
    ]
